### ISSUE TITLE
Can't battle

### ISSUE THREAD

**Issue by diits3** [Deltric/Generations#1]
What is the bug? Every time I try to battle a pokemon on an npc, it flashes with me getting xp to my pokemons stats, and then just closes the battle instantly. You can see some text on the bottom of the screen, and the words "stop spectating" on the top of the screen.
What are the steps to reproduce the bug? I don't know, I just played the game normally, searching for a jigglypuff. It just happened for no reason.
What version of Pixelmon and Forge are you on? Minecraft forge version 1.12.2, and Pixelmon Generations version 1.12.2 8.3.0. 
Please provide any screenshots or crash reports if needed. The game isn't crashing, but I made a short video that was too big to upload on here, so I uploaded it to youtube. 
https://www.youtube.com/watch?v=fakL9CMTpQs

Thank you for your help! : )

**Comment by Stampede2011** [comment]
I've seen this happen on a testing server before. Could you provide the log file when this was happening (in the "logs" folder of your game files)? Also, does closing your game and re-opening it fix the issue?

**Comment by Dysth** [comment]
@diits3 Heya, we need some more info from you on this

**Comment by Dysth** [comment]
Closing due to no response in a week
