### ISSUE TITLE
Unenchanting Running boots

### ISSUE THREAD

**Issue by SplatHero** [Deltric/Generations#100]
**What is the bug?**
Clear description of what the bug is
Old Running boots unenchanting when being crafted back into new running boots

**What are the steps to reproduce the bug?**
Clear steps on how to reproduce the bug
1. Enchant old running boots
2. Go over to a crafting table and turn the old into new boots

**What version of Pixelmon and Forge are you on?**
Your Pixelmon version and Forge version
Pixilmon: 8.4.2.
Forge: 1.12.2-14.23.5.2847

**Please provide any screenshots or crash reports if needed.**
If you have any screenshots that could visualize the bug

**Comment by Cavans99** [comment]
Sorry for the intromission, but isn't that how minecraft itself works?
Like Crafting an enchanted pickaxe with another pickaxe of the same material (to repair it) will give an unenchanted pickaxe as output.

**Comment by Lypaka-Dev** [comment]
Is that how it works? I don't really do vanilla stuff enough to know. I asked him to report it here because I was thinking more of the anvil thing (granted anvils and crafting tables are two different mechanics) where fixing tools doesn't wipe the enchantments.

**Comment by Stampede2011** [comment]
This is normal behavior! Crafting tables normally do remove enchants when combining where anvils don't
