### ISSUE TITLE
New special texture

### ISSUE THREAD

**Issue by Tommy06Pag** [Deltric/Generations#112]
Hi, I would like to suggest these possible special texture based on pokemon series for jynx (S2 ep.8) and gengar, alakazam, jigglypuff (S2 ep.17)
![jynx](https://user-images.githubusercontent.com/81684661/116071155-d8a19600-a68d-11eb-9cff-2f2fe18fa1bb.PNG)
![gengar](https://user-images.githubusercontent.com/81684661/116071163-db9c8680-a68d-11eb-9c13-e5cab5ccd846.PNG)
![alakazam](https://user-images.githubusercontent.com/81684661/116071172-ddfee080-a68d-11eb-878f-408eec85e339.PNG)
![jiggly](https://user-images.githubusercontent.com/81684661/116071184-e0613a80-a68d-11eb-8bd8-52cdf8b0a1cd.PNG)

**Comment by Deltric** [comment]
We aren't accepting suggestions for special textures on the GitHub.
