### ISSUE TITLE
New ideas

### ISSUE THREAD

**Issue by wilian003** [Deltric/Generations#119]
Hello. idk if you are a dev of pixelmon, just wanna to make you a question if you are. Have you ever thinked about make a digimon mod like pixelmon ? I think this will be great, there is no mod about Digimon who looks cool as pixelmon.

**Comment by Dysth** [comment]
Unfortunately you'd have to find a different team, we barely have enough time to keep up with all the content Pokemon has, let alone another version for 1400 creatures
