### ISSUE TITLE
Pokémon Special Textures

### ISSUE THREAD

**Issue by JadeFairall** [Deltric/Generations#128]
A sidemod for special textures for Pokémon for solo worlds. For example the special textures on The Crew pixelmon server - the rainbow Eevees and all the galaxy skins as these are a really cool feature that aren't available currently. 

(Not sure how to add enhancement label)

**Comment by Stampede2011** [comment]
Those special textures you see on other servers, like The Crew server, are custom ones to that server using some special plugins. They may eventually get implemented into the mod if the creators so choose

**Comment by Dysth** [comment]
I'd love to get them soon as well, however, unfortunately we can't currently accept special texture requests on this issue tracker or we'd have hundreds of requests and too much to keep track of- but I can say we've discussed trying to get them and/or making a new set in a similar style
