### ISSUE TITLE
Breeding with ranchblocks broken.

### ISSUE THREAD

**Issue by ItzFluffyFox** [Deltric/Generations#134]
The bug seems to just be the ranch block breeding due to /breed working. The bug makes it so you may put pokemon in the ranch block but they will not show hearts above their head, and they also will not breed and make an egg, originally I thought it would only be on multiplayer servers, but it seems to also be on single player worlds, at least creative ones. The only thing to fix this is silver hourglasses which are rare, at least I haven't gotten one in survival.

It is a bug with breeding in general. You give the pokemon a place they would like, and another pokemon they will breed with, it will say their love grows any speed doesn't matter but hearts will not appear over their heads, and even after waiting a while they do not make an egg

I am on the most recent update for pixelmon from the technic launcher.

Screenshots attached will be from a solo world first, and then a multiplayer world to show it is broken on both.

If it is only specific servers I've had issues in Pokecraft, Pixelmon Harmony, and a survival world solo.

![Breeding](https://user-images.githubusercontent.com/83845637/117516151-e1337f80-af5d-11eb-89db-3385ba54d03b.png)
![Breeding Broken](https://user-images.githubusercontent.com/83845637/117516154-e690ca00-af5d-11eb-9cd0-aa1b6baf6b3d.png)

**Comment by Deltric** [comment]
I've tested the ranch block without speeding it up through hour glasses and it completely worked through all stages + made an egg at the end. Some things you may want to consider

- You have to be pretty close to the ranch block for it to progress
- Breeding is not inherently fast without boosting it through hour glasses
- Wool is not the fastest material for Normal type, crafting table and cake is by default.
