### ISSUE TITLE
NPC trainer lvl 0

### ISSUE THREAD

**Issue by Tommy06Pag** [Deltric/Generations#139]
**What is the bug?**
NPC trainer can spawn with lvl 0 and you can't challenge them.

**What are the steps to reproduce the bug?**
You need to find a lvl 0 npc

**What version of Pixelmon and Forge are you on?**
Last official version on tecnich launcher

**Please provide any screenshots or crash reports if needed.**
https://youtu.be/3Ybnq383G3I

**Comment by Deltric** [comment]
This is my server in the video and likely is just a problem with our NPC configs being outdated. Haven't ever seen this in singleplayer and asked another owner if they've seen it.
