### ISSUE TITLE
Ruby block bug leads to uncraftable bottle stem

### ISSUE THREAD

**Issue by Tomu1572** [Deltric/Generations#140]
**What is the bug?**
Clear description of what the bug is

The ruby block is bugged out when using with Biomes O Plenty mod. Basically, there is a "ruby block" in Pixelmon mod AND Biomes O plenty. But apparently, If we use a ruby from the Pixelmon mod. It will be craft into a "ruby block" from Biomes O Plenty mod. In which makes it impossible to craft a Bottle Stem for Hoopa.

**What are the steps to reproduce the bug?**
Clear steps on how to reproduce the bug

Use a ruby from Pixelmon and try to craft it into ruby block.

**What version of Pixelmon and Forge are you on?**
Your Pixelmon version and Forge version

8.4.2, forge1.12.2-14.23.5.2847

**Please provide any screenshots or crash reports if needed.**
If you have any screenshots that could visualize the bug

![2021-05-10_23 48 22](https://user-images.githubusercontent.com/83832206/117696204-3cc66d00-b1eb-11eb-9ee2-0f03a5d37fc1.png)

![2021-05-10_23 48 25](https://user-images.githubusercontent.com/83832206/117696240-44861180-b1eb-11eb-942a-cb811193292a.png)

**Comment by Stampede2011** [comment]
This can be self remedied by deleting the `ruby_block.json` file out of the `\assets\biomesoplenty\recipes\` folder of the Biomes o' Plenty JAR file, which can be edited using WinRar or something similar.
