### ISSUE TITLE
BiomesOPlenty log glitch bug

### ISSUE THREAD

**Issue by king-glitch** [Deltric/Generations#145]
**What is the bug?**
With BiomesOPlenty Log, When you push axe and any of BiomesOPlenty log it will duplicates the axe.

**What are the steps to reproduce the bug?**
remove item after craft.

**What version of Pixelmon and Forge are you on?**
Pixelmon: 8.4.2
Forge: 14.23.5.2855

**Please provide any screenshots or crash reports if needed.**
![image](https://user-images.githubusercontent.com/58404132/117949690-97231300-b33c-11eb-8e14-ce732459caf0.png)

**Comment by Stampede2011** [comment]
This does not seem like a Pixelmon Generations issue! The pack by default does not contain the mods that adds an Axe + Wood recipe, so it must be caused by an added mod.

**Comment by king-glitch** [comment]
> This does not seem like a Pixelmon Generations issue! The pack by default does not contain the mods that adds an Axe + Wood recipe, so it must be caused by an added mod.

Pixelmon generation default generate this mod. the latest version is 2443 on the mod webiste. but on pixelmon generation version is 2444. that's why I asked here.

**Comment by Dysth** [comment]
https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty/files/2842510
Can you elaborate a little more?
I'm not sure exactly what should be tested to try to reproduce. Also, is this on a server or singleplayer?

**Comment by Deltric** [comment]
This issue is not Pixelmon specific and is a bug from the other mod you have added.
