### ISSUE TITLE
Pokespawn can't configure IVS, EVS

### ISSUE THREAD

**Issue by king-glitch** [Deltric/Generations#146]
**What is the bug?**
With pokespawn can't configure IVS nor EVS
with command /pokespawn [pokemonName] ivhp:2 lvl:1 s
**What are the steps to reproduce the bug?**
I don't know.

**What version of Pixelmon and Forge are you on?**
8.4.2
14.23.5.2855

**Comment by Cavans99** [comment]
the command you are looking for is /pokespawn <pokémon> ivs:31/31/31/31/31/31
This will give you a 100% ivs pokemon.

The 6 values need to be all specified and are in order: HP/Atk/Def/Sp.Atk/Sp.Def/Speed

**Comment by king-glitch** [comment]
> the command you are looking for is /pokespawn <pokémon> ivs:31/31/31/31/31/31
> This will give you a 100% ivs pokemon.
> 
> The 6 values need to be all specified and are in order: HP/Atk/Def/Sp.Atk/Sp.Def/Speed

Oh, Thank you !!!
