### ISSUE TITLE
Pheromosa Triple Axel Move tutor bug (Multiplayer)

### ISSUE THREAD

**Issue by Frissonille** [Deltric/Generations#149]
**What is the bug?**
Pheromosa can't learn Triple Axel because nothing happens when clicking on the move via a move tutor even tho it says "can learn" 

**What are the steps to reproduce the bug?**
-Get a move tutor with Triple Axel
-Select Pheromosa
-Select Triple Axel, see "can learn"
-Nothing happens (edit, only happens in multiplayer for me)

**What version of Pixelmon and Forge are you on?**
Pixelmon v8.4.2 and forge 8.0.99.99 (1.12.2)

**Please provide any screenshots or crash reports if needed.**

**Comment by Frissonille** [comment]
![Pherororo](https://user-images.githubusercontent.com/84086155/117997262-1ca9c180-b343-11eb-8da3-a5adb0668c13.gif)

**Comment by Stampede2011** [comment]
I cannot seem to replicate this issue in both singleplayer, a multiplayer test server, or a multiplayer public server. Might be specific to the Pheromosa you have being glitched out?

**Comment by Frissonille** [comment]
> I cannot seem to replicate this issue in both singleplayer, a multiplayer test server, or a multiplayer public server. Might be specific to the Pheromosa you have being glitched out?

oh well, I'll close this then. Kinda weird that it only happened to this particular Pheromosa/Multi Server
