### ISSUE TITLE
New items suggestion

### ISSUE THREAD

**Issue by Tommy06Pag** [Deltric/Generations#151]
Hi, as we know orbs are an important pillar to summon some legendaries, but sometimes it's boring and repetitive to kill all those pokemon. So I thought about possible options:
- a charm that reduces the durability of the orb every X seconds/minutes. ( with configurable section)
- a charm that reduces the orb by 2 when you kill a pokemon (or npc for the secret armor scroll).
- an item that charge the orb instantly.

**Comment by Deltric** [comment]
This specific suggestion seems better as a plugin feature rather than mod feature. They need to be long tasks to not make it way too easy to get a legendary.

**Comment by Tommy06Pag** [comment]
Yeah you are right that they need to be long tasks, but when you have a lot of orb it's boring.
When you have to summon them for the first time is fine, but during the second time or more is really boring, especially because you can't charge more orbs at the same time.

**Comment by Deltric** [comment]
It would be unbalanced if you could charge multiple at a time or also be faster to charge orbs after doing it a first time. This is intentionally to not allow people to churn out legends really quickly.
