### ISSUE TITLE
Cant go in a server ''fatally missing registry entries''

### ISSUE THREAD

**Issue by coolboi123456** [Deltric/Generations#154]
**What is the bug?**
i cant go in a server

**What are the steps to reproduce the bug?**

**What version of Pixelmon and Forge are you on?**
8.2.0

**Please provide any screenshots or crash reports if needed.**
![2021-05-17](https://user-images.githubusercontent.com/84341472/118526822-ea340600-b740-11eb-8c8c-30b2b761cfe1.png)

**Comment by Tommy06Pag** [comment]
Probably the problem is that the server is running another version of pixelmon generations, have you tried to used the last version (8.4.2)?

**Comment by Deltric** [comment]
You have to have the same Pixelmon version as the server. Which is why it's not letting you connect.
