### ISSUE TITLE
Just a stupid idea about legends

### ISSUE THREAD

**Issue by Cavans99** [Deltric/Generations#156]
As many Legends have different summoning lores depending if you are playing the games, watching the anime or watching a movie (ex: Lugia requires the silver wing + tidal bell in the game, while the three treasures + melody flute in the movie), why limiting to only one?

Giving a legend different summoning ways could make the game more immersive, making each player choose his own path.

**Comment by Deltric** [comment]
This creates a balancing problem as each method for the same Pokemon would have to share the same difficulty to obtain or it could be broken. Also creates more confusion as you can't just give a player 1 straight answer when asked how to spawn a legend. For those reasons we won't be adding multiple ways for 1 legend but we're likely to add methods for the legendaries missing theirs.

**Comment by Cavans99** [comment]
Oh true, balancing is a big issue I didn't really think about; people would always go with the easiest/fastest way.
I'm not really sure about the confusion created, as, in case no one remembers all the steps, the wiki could help clarify things; but if you don't think it would be a good idea I'm fine with it!

I've never been a big Pokémon fan, but really love this mod, so not today of course, but maybe in the future, I hope even more immersivity will be added.
