### ISSUE TITLE
Sphax compatibility for pixelmon generations

### ISSUE THREAD

**Issue by Ruddiestelm575** [Deltric/Generations#174]
Could we get a sphax texture add on made for pixelmon generations to be added on to the sphax base pack and the sphax BOP addon , there are a few suggestions on the sphax forums but I thought it would be worth asking here as I know it’s likely they you could get it made as mod developers. There are a few basic ones for other pixelmon mod packs but a lot of the textures do not work as intended. I think it would be brilliant to have an option to have different textures and potentially different sounds for the pokes to support the mod.

**Comment by Deltric** [comment]
Its not feasible to ask us to make textures for others resource packs. The authors of that resource pack are able to do it themselves or anyone in the community.
