### ISSUE TITLE
pokestats command free win

### ISSUE THREAD

**Issue by Conno2429** [Deltric/Generations#177]
**What is the bug?**
If a player forfeits or does /endbattle on a battle with another player, both players receive a win in pokestats. 

**What are the steps to reproduce the bug?**
Go into battle, then either do /endbattle or forfeit the match. Use the command /pokestats both before and after the testing. 

**What version of Pixelmon and Forge are you on?**
Pixelmon Generations v8.4.2, forge 1.12.2-14.23.5.2847

**Please provide any screenshots or crash reports if needed.**
![Capture](https://user-images.githubusercontent.com/41807570/120939967-8c576600-c6cf-11eb-9c4e-b61522c0380d.PNG)

**Comment by Deltric** [comment]
There's a setting in your hocon to change the default battle ruling. That'll fix this.
