### ISSUE TITLE
Untiered Battles Ban Pokemon

### ISSUE THREAD

**Issue by ViolaAntonier** [Deltric/Generations#188]
**What is the bug?**
Battling with battle rules on, tier "Untiered" ban certain Pokemon, including Toxapex and Sableye.

**What are the steps to reproduce the bug?**
Battle a trainer with battle rules on, tier "Untiered".

**What version of Pixelmon and Forge are you on?**
Current Technic Launcher, v8.5.0

**Comment by Dysth** [comment]
Fixed in 8.5.1 release
