### ISSUE TITLE
New Horde Mechanic is glitched? 

### ISSUE THREAD

**Issue by Arrikanez** [Deltric/Generations#194]
**What is the bug?**
_When I come across a Horde encounter, my pokemon and the pokemon I'm fighting all disappear. I can see names and moves, but the pokemon itself is not visible. This might be an issue for shiny hunters who want to chain hordes..._

**What are the steps to reproduce the bug?**
_Sit in Pixelmon Grass until a Horde encounter spawns. Then you'll see what I mean._

**What version of Pixelmon and Forge are you on?**
_Pixelmon Version 8.5.1 - and Technic Launcher Version 4.652_

**Please provide any screenshots or crash reports if needed.**
![PixelmonBug](https://user-images.githubusercontent.com/4131538/121894902-ac011680-cced-11eb-8146-68cd8e6df141.jpg)

**Comment by Lypaka-Dev** [comment]
The sprite of the Pokemon shows shiny in its bar next to its health. The Pokemon entities themselves are not spawned when a horde battle goes off for FPS purposes.

**Comment by Lypaka-Dev** [comment]
https://prnt.sc/12l70bl
