### ISSUE TITLE
The game crashes during flying to the sky and create a new world

### ISSUE THREAD

**Issue by Blackkie** [Deltric/Generations#197]
**What is the bug?**
The game always crashes when flying to the sky to the new area, and creating new world. I think it might be because of chunk loading issue. Those 2 occurred on single player.

**What are the steps to reproduce the bug?**
In case of flying on the sky:
Mounting on a fly-able Pokemon, flying to the sky randomly (e.g. flying to the new area that chunk unloaded) , and the game crashes. 

In case of creating new world:
Just create new world, and the game crashes. I already tried to load that newly-created world again, the game still crashes.

**What version of Pixelmon and Forge are you on?**
Pixelmon 8.5.1 and Forge forge-1.12.2-14.23.5.2854

**Please provide any screenshots or crash reports if needed.**
[crash-2021-06-16_22.27.20-server.txt](https://github.com/Deltric/Generations/files/6664240/crash-2021-06-16_22.27.20-server.txt) In case of flying to the sky issue.

[crash-2021-06-16_22.57.13-server.txt](https://github.com/Deltric/Generations/files/6664313/crash-2021-06-16_22.57.13-server.txt) In case of create new world issue.

**Comment by Stampede2011** [comment]
This is a known bug in the latest version! There is an issue report already started for (#187). A temporary fix was implemented, which is commented there.
