### ISSUE TITLE
Ball throw on grass Bug

### ISSUE THREAD

**Issue by Cavans99** [Deltric/Generations#2]
- **What is the bug?**
You can't throw your Pokémon out of the ball, if it lands on grass.
I know it's an old bug and feels kinda nostalgic, but can be really annoying sometimes.

- **What are the steps to reproduce the bug?**
Try to throw your Pokémon out of the ball, making it land on grass (tall or not).

- **What version of Pixelmon and Forge are you on?**
Pixelmon 8.3.0, Forge 14.23.5.2847

- **Please provide any screenshots or crash reports if needed.**
https://user-images.githubusercontent.com/81328680/112376116-5a478200-8ce4-11eb-994d-c4c446a00f71.mp4

**Comment by Deltric** [comment]
Fixed in 8.4.2
