### ISSUE TITLE
Zygarde 100% and Cube

### ISSUE THREAD

**Issue by HeXaNi** [Deltric/Generations#20]
**What is the bug?**
Clear description of what the bug is
If you absorb a zygarde with power construct, it only returns 50 cells. If you try to absorb a zygarde in 100% form from using pokemon editor item, you are told that there is not enough space.
**What are the steps to reproduce the bug?**
Clear steps on how to reproduce the bug
Get a zygarde with either power construct or in 100% form and try to absorb it with cube.
**What version of Pixelmon and Forge are you on?**
Your Pixelmon version and Forge version
Pixelmon 8.4.1
**Please provide any screenshots or crash reports if needed.**
If you have any screenshots that could visualize the bug

**Comment by Dysth** [comment]
Passed BETA tests, will be fixed in next update. Thanks for reporting
