### ISSUE TITLE
Arceus can still spawn in the wild

### ISSUE THREAD

**Issue by Cavans99** [Deltric/Generations#206]
**What is the bug?**
Arceus can still spawn randomly in the wild. (mod updated and configs regenerated)

**What are the steps to reproduce the bug?**
Find a biome that previously allowed Arceus to spawn and do /checkspawns. (in this case Grassland)
Or check mod files for spawning.

**What version of Pixelmon and Forge are you on?**
Pixelmon 8.5.1, Forge 14.23.5.2855

**Please provide any screenshots or crash reports if needed.**
![Arceus](https://user-images.githubusercontent.com/81328680/123302800-5d3d5300-d51d-11eb-9fc4-8a1b73f5a7e5.png)

**Comment by Deltric** [comment]
Its meant to still have a spawn, the shrine is just another way of obtainment. Servers are able to remove the spawn if they wish to only have it through shrine.
