### ISSUE TITLE
The Case of the Wrong Meowth Sprite

### ISSUE THREAD

**Issue by BillTheSest** [Deltric/Generations#21]
**What is the bug?**
Galarian Meowth party sprite shows the shiny version. Shiny version may or may not show the normal version, I haven't found one yet.

**What are the steps to reproduce the bug?**
Catch a Galarian Meowth, then look at its party icon.

**What version of Pixelmon and Forge are you on?**
Pixelmon 8.4.2, Forge 14.23.5.2847

**Please provide any screenshots or crash reports if needed.**
![image](https://user-images.githubusercontent.com/81494713/112738028-b228f780-8f35-11eb-9a71-6795cc5ed701.png)

**Comment by Stampede2011** [comment]
From what I can tell, the sprite in your party for Meowth is the non-shiny Galarian one. The shiny version is more yellow!

**Comment by BillTheSest** [comment]
Forgot to respond, my bad. Thanks!
