### ISSUE TITLE
No honey for you my friend

### ISSUE THREAD

**Issue by maddogmitch** [Deltric/Generations#22]
**What is the bug?**
Kakuna, Beedrill, Combee, Vespiqueen are not dropping honey when defeated

**What are the steps to reproduce the bug?**
Find above mentioned pokemon, defeat the pokemon.

**What version of Pixelmon and Forge are you on?**
Pixelmon 8.4.2, using technic launcher so can't find the forge version

**Comment by Stampede2011** [comment]
There appears to be an error with the DropEvent that is preventing the drop. [Error report here](https://pastebin.com/vJ91ZUtq)
