### ISSUE TITLE
Silver Bottlecaps Not Registering

### ISSUE THREAD

**Issue by PowerKong** [Deltric/Generations#222]
What is the bug?
When trying to use a silver bottlecap on my server, it doesn’t alter IV’s or read the fact that the IV’s are 31. For example, on my 5/6 (5 IV’s being 31) it says that it can be used for all 6 slots, and when I chose the non-31 slot, it uses the bottlecap without altering the IV, if that makes sense.
What are the steps to reproduce the bug?
Just using a silver bottlecap produces this bug on my server.

What version of Pixelmon and Forge are you on?
Pixelmon: 1.12.2-8.5.1
Forge: 1.12.2-14.23.5.2854

Please provide any screenshots or crash reports if needed.
None now but could provide if needed later.

**Comment by Stampede2011** [comment]
Bottle Caps do not actually edit the actual IV stats! They only modify the battle used IV stats as to not affect breeding IV stats, at least as far as I am aware. This is why you don't see a change in the actual numbers, like when using /ivs
