### ISSUE TITLE
Sad Mega Rayquaza

### ISSUE THREAD

**Issue by Tomu1572** [Deltric/Generations#232]
**What is the bug?**
Clear description of what the bug is
Rayquaza can't mega evolve. The button seems invisible, but u can still press it. But even if u try to press the button that is invisible there is still a sound of clicking but still it can't mega evolve.

**What are the steps to reproduce the bug?**
Clear steps on how to reproduce the bug
Having Rayquaza in the party. Teach it the move Dragon Ascent. Then use it to slaughter some pokemon and try to mega evolve.

**What version of Pixelmon and Forge are you on?**
Your Pixelmon version and Forge version
8.5.1, 1.12.2-forge-14.23.5.2855

**Please provide any screenshots or crash reports if needed.**
If you have any screenshots that could visualize the bug

**Comment by Cavans99** [comment]
Does it hold a z-crystal? It can't mega evolve if it holds one.

**Comment by Tomu1572** [comment]
> Does it hold a z-crystal? It can't mega evolve if it holds one.

Nope, I tried it when it's not holding item, and I tried to spawn a wild one and just teach it the move dragon ascent, and I tried putting some random item on it like Choice Band and stuff. but still can't :(
