### ISSUE TITLE
Curry experience config

### ISSUE THREAD

**Issue by AntarticaFr** [Deltric/Generations#234]
**What is the bug?**
The config option "curryTriggersLevelEvent" does not seem to work. Even if I deactivate it, curry still give experience to Pokémon.

**What are the steps to reproduce the bug?**
Put "curryTriggersLevelEvent" to false in config et try to give a Pokémon some curry

**What version of Pixelmon and Forge are you on?**
Pixelmon: 8.5.1 ; forge: 1.12.2 - 14.23.5.2854

**Please provide any screenshots or crash reports if needed.**
Nothing here but the helper A_fish on the discord tried and had the same bug

Please let me know if you need any more information

**Comment by Deltric** [comment]
That config option is only for not letting it run the API event for level up. For instance in a plugin that gives some kind of exp for pokemon leveling if you didn't want it to trigger from that then it would stop it. not intended to actually stop the giving of experience.
