### ISSUE TITLE
A bug with the ohko moves

### ISSUE THREAD

**Issue by Marco152269** [Deltric/Generations#24]
**What is the bug?**
I'm not sure but i think the ohko moves are bugged,and this why? Because i used fissure with event camerupt and the move hitted at the 100%  for 14 times (One time missed)

**What are the steps to reproduce the bug?**
Use a ohko move

**What version of Pixelmon and Forge are you on?**
The Pixelmon version Is the 8.4.1

**Please provide any screenshots or crash reports if needed.**
If you have any screenshots that could visualize the bug

**Comment by Dysth** [comment]
Hi @Marco152269 , I can't seem to reproduce this. It's failing at a consistent rate as it should be (Fissure)
Can you please provide the full setup of the Pokemon?

**Comment by Dysth** [comment]
Closing due to no response in a week, and can't reproduce
