### ISSUE TITLE
Kubfù and urshifù bug

### ISSUE THREAD

**Issue by Marco152269** [Deltric/Generations#25]
**What is the bug?**
If i try ti catch kubfù or urshifù the game crash  and i Lost them

**What are the steps to reproduce the bug?**
For the bug you Need to summon and catch kubfù or urshifù

**What version of Pixelmon and Forge are you on?**
The version Is the 8.4.2

**Please provide any screenshots or crash reports if needed.**
If you have any screenshots that could visualize the bug

**Comment by Stampede2011** [comment]
I cannot seem to replicate your issue. Could you provide the crash report that should have been generated in the "crash-reports" folder of your game files?

**Comment by Dysth** [comment]
@Marco152269 We need your logs if you could please provide them

**Comment by Dysth** [comment]
Closing due to no response in a week and can't reproduce
