### ISSUE TITLE
Rockruff evolution bugs

### ISSUE THREAD

**Issue by Cavans99** [Deltric/Generations#30]
**What is the bug?**
Rockruff evolution issues.

**What are the steps to reproduce the bug?**
- Making an HA (Steadfast) Rockruff evolve into any of its evolutions will make the game crash and will cause a strange error with battles (Fixed after restarting the launcher)
(The message "Couldn't load Pokémon's moves" will appear in chat when trying to battle any wild Pokémon with any member of your team).
- Evolving a "Own Tempo" Rockruff will cause the evolution to have the Hidden Ability.
- Rockruff will evolve into Midnight form even before [dusk time](https://minecraft.fandom.com/wiki/Daylight_cycle#Sunset.2Fdusk) has ended and even if Rockruff doesn't have "Own Tempo" ability.

**What version of Pixelmon and Forge are you on?**
Pixelmon 8.4.2, Forge 14.23.5.2854

**Please provide any screenshots or crash reports if needed.**
[Crash report](https://pastebin.com/iimxXzTa)

**Comment by Dysth** [comment]
Passed BETA tests, will be fixed in next update. Thanks for reporting
