### ISSUE TITLE
Activiting a Shrine

### ISSUE THREAD

**Issue by MageFX** [Deltric/Generations#32]
**What is the bug?**
If your Slot 1 Pokemon is fainted you are unable to use the shrine even if the rest of your party is in good health.

**What are the steps to reproduce the bug?**
Activate any shrine with Slot 1 fainted.

**What version of Pixelmon and Forge are you on?**
8.4.2

**Please provide any screenshots or crash reports if needed.**
n/a

**Comment by Dysth** [comment]
fixed, pending beta
