### ISSUE TITLE
Battle bond NPC Trainers

### ISSUE THREAD

**Issue by ItsHypers** [Deltric/Generations#34]
**What is the bug?**
Whenever you try to use a battle bond greninja in an NPC and it switches to it, it creates an error in console and closes the battle

**What are the steps to reproduce the bug?**
Create a battle NPC, give it a greninja with the battle bond ability, fight it

**What version of Pixelmon and Forge are you on?**
8.4.2

**Please provide any screenshots or crash reports if needed.**
If you have any screenshots that could visualize the bug

**Comment by Dysth** [comment]
Closing due to no response in a week and can't reproduce
