### ISSUE TITLE
[Suggestion] Chisel support 

### ISSUE THREAD

**Issue by ZIFIXLeDebutant** [Deltric/Generations#35]
The compatibility of Pixelmon with Biome 'O Plenty was a very good idea. It would be nice if Chisel is present to give a wide choice of decorations

**Comment by Deltric** [comment]
We won't be adding more content mods like this to the modpack. Biomes O Plenty was an exception with how diverse it could make the worlds itself. Always welcome to throw it into your mods folder and play alongside it.
