### ISSUE TITLE
EmojiCord not rendering stickers

### ISSUE THREAD

**Issue by DarkTimers** [Deltric/Generations#36]
1. EmojiCord modification that bring discord stickers to minecraft can't render stickers because of rendering abilities of pixelmon generations
2. Install modification - visit game - open chat - look at the right bottom part and you will se no image but only text
3. forge-1.12.2-14.23.5.2847 , pixelmon - 8.4.2
4. Crash Report is clean, the game doesn't crash

**Comment by Deltric** [comment]
EmojiCord is incompatible with the mod in 1.12.2
Unlikely to be fixed for this Minecraft version.
