### ISSUE TITLE
Inventory balance is unreliable and has clipping issues

### ISSUE THREAD

**Issue by Lukeno94** [Deltric/Generations#40]
**What is the bug?**
1: Often when a player first logs in, their balance reports as only being 999,999 even when it is substantially higher than that. /bal and similar commands always report the correct value, so it appears that it is an issue solely with the GUI. This may be Pixelmon specific or an issue between it and Economy Lite.

2: Any value longer than 7 digits will have clipping issues. Since most plugins I'm aware of go up to 9 digits, the GUI should be redesigned to accommodate that.

**What are the steps to reproduce the bug?**
Open your inventory and check the listed balance.

**What version of Pixelmon and Forge are you on?**
Generations 8.4.2 and Forge 2851

**Please provide any screenshots or crash reports if needed.**
![image](https://user-images.githubusercontent.com/81629405/112996084-c7836900-9163-11eb-94ed-fe7d76d95797.png)

**Comment by Stampede2011** [comment]
I can verify that the bug regarding 999,999 being the maximum shown in the money part of the inventory after logging in happens, but I am unable to find a way to reproduce it consistently. Seems to go away after some short time. The other issue can be verified by setting your balance above 9,999,999.

**Comment by Deltric** [comment]
It's capped to a certain value for space reasons and not being redone currently.
