### ISSUE TITLE
Wondertrade Pool has an incorrect sprite

### ISSUE THREAD

**Issue by Lukeno94** [Deltric/Generations#41]
**What is the bug?**
The next page button in the /wt pool GUI is the wrong way around.

**What are the steps to reproduce the bug?**
Open /wt pool

**What version of Pixelmon and Forge are you on?**
Generations 8.4.2, Forge 2851

**Please provide any screenshots or crash reports if needed.**
![image](https://user-images.githubusercontent.com/81629405/112998108-a15ec880-9165-11eb-9320-9a5d2fd0807f.png)

**Comment by Deltric** [comment]
This isn't the official wonder trade side mod, please don't report other plugins here.
