### ISSUE TITLE
Kyogre Shrine dosent work

### ISSUE THREAD

**Issue by Jaackla** [Deltric/Generations#44]
**What is the bug?**
Clear description of what the bug is
Spawning the kyogre with the shrine does not work since the latest update

**What are the steps to reproduce the bug?**
Clear steps on how to reproduce the bug
Get a full blue orb, throw out mega ray next to the kyogre shrine, click the orb on the shrine then the kyogre should spawn but dosent

**What version of Pixelmon and Forge are you on?**
Your Pixelmon version and Forge version
Latest Pixelmon - Not Sure

**Please provide any screenshots or crash reports if needed.**
If you have any screenshots that could visualize the bug
![image](https://user-images.githubusercontent.com/36846537/113067054-8fa41200-91b3-11eb-86b7-3bdf6f07d41d.png)

**Comment by Deltric** [comment]
Sorted in Discord, reopen if this issue persists.
