### ISSUE TITLE
Dynamax lvl's

### ISSUE THREAD

**Issue by Explovision** [Deltric/Generations#55]
**What is the bug?**
the dynamax lvls are not giving the 5% hp boost that they say it gives for me it only gives a boost of 3 1/3%.

**What are the steps to reproduce the bug?**
to reproduce this u have to give a pokemon a dynamax candy

**What version of Pixelmon and Forge are you on?**
 i'm using technic launcher and i'm on pixelmon version 8.4.2

**Please provide any screenshots or crash reports if needed.**

![candy](https://user-images.githubusercontent.com/81826644/113443078-86a08400-93f1-11eb-9c6c-879c05543e73.JPG)
![devil](https://user-images.githubusercontent.com/81826644/113443094-8e602880-93f1-11eb-9246-386a8929f841.JPG)
![dyna candy](https://user-images.githubusercontent.com/81826644/113443152-acc62400-93f1-11eb-8f66-450f7d15b206.JPG)
![dyna devil](https://user-images.githubusercontent.com/81826644/113443155-afc11480-93f1-11eb-81f9-f24b2726625f.JPG)

**Comment by Dysth** [comment]
Heya,
We did some testing and it appears fine
Dynamax Level 10:
https://gyazo.com/cfafcd7a6b87d8db45e01154a74bf45c
Dynamax Level 10 in game: https://gyazo.com/f311c351f9ec52593bdfbd42578f8afc

For your Dubwool: 348 Base HP + (348*.75) = 609

**Comment by Explovision** [comment]
thanks for reacting to this.
it seems like i made a mistake so sorry for any inconvenieces it may have caused.
and once again thanks for responding.

**Comment by Dysth** [comment]
No problem at all, we're all human
