### ISSUE TITLE
Lots of vanilla Minecraft items are missing descriptions in NPC shops

### ISSUE THREAD

**Issue by Lukeno94** [Deltric/Generations#60]
**What is the bug?**
Lots of vanilla Minecraft items are missing descriptions in NPC shops

**What are the steps to reproduce the bug?**
If you go up to any NPC shopkeeper that is selling vanilla Minecraft items, odds are that item will say "No description found for item: x"

**What version of Pixelmon and Forge are you on?**
Generations 8.4.2 and Forge 2854

**Please provide any screenshots or crash reports if needed.**
![2021-04-04_12 44 10](https://user-images.githubusercontent.com/81629405/113507620-94feb500-9543-11eb-8764-17b3a467192a.png)
![2021-04-04_12 44 06](https://user-images.githubusercontent.com/81629405/113507622-95974b80-9543-11eb-906d-3978bb7f43ba.png)
![2021-04-04_12 44 09](https://user-images.githubusercontent.com/81629405/113507623-962fe200-9543-11eb-9f50-21cdf539d9f4.png)

**Comment by Deltric** [comment]
This isn't a bug, this is because you've made shops with these custom items/blocks.

**Comment by Deltric** [comment]
Closing as we aren't responsible for typing up descriptions to every item in the game.
Redirect people to vanilla wiki.
