### ISSUE TITLE
Zygarde Cube has no lore attached

### ISSUE THREAD

**Issue by Lukeno94** [Deltric/Generations#62]
**What is the bug?**
Zygarde Cube has no lore attached to give a description of the item

**What are the steps to reproduce the bug?**
Hover over a Zygarde Cube; it won't give you the option to press shift to display more information

**What version of Pixelmon and Forge are you on?**
Generations 8.4.2 and Forge 2854

**Please provide any screenshots or crash reports if needed.**
![2021-04-04_13 06 49](https://user-images.githubusercontent.com/81629405/113508239-c331c400-9546-11eb-9414-b66044d5a000.png)

**Comment by Dysth** [comment]
Passed BETA tests, will be fixed in next update
