### ISSUE TITLE
Zygarde Machine has the wrong hitbox

### ISSUE THREAD

**Issue by Lukeno94** [Deltric/Generations#63]
**What is the bug?**
Zygarde Machines have an incorrect hitbox - you can stand inside them. Fine for cosplaying as Zygarde, but not much else!

**What are the steps to reproduce the bug?**
Place Zygarde Machine, stand inside it.

**What version of Pixelmon and Forge are you on?**
Generations 8.4.2 and Forge 2854

**Please provide any screenshots or crash reports if needed.**
![2021-04-04_19 57 22](https://user-images.githubusercontent.com/81629405/113518751-22f89100-9580-11eb-9d28-6a9b705c0233.png)

**Comment by Deltric** [comment]
This isn't really an issue and is very nitpicky. Please avoid making issues like this in the future unless a serious issue instead of joking reports.

**Comment by Lukeno94** [comment]
This wasn't a "joke" report and I find it inappropriate that you deemed it as such. This is a bug, plain and simple; you have a two block tall item with a one block tall hitbox. Making a lighthearted remark in the bug report doesn't magically stop it being a bug either.

**Comment by Deltric** [comment]
You can slightly clip into every block in Minecraft, congratulations should rewrite the entire collision system of the base game? Spamming the GitHub with irrelevant issues is a waste of our time when you open a issue for example that we should make a item/block description for every single item and block in Minecraft and its a bug if we don't. There's nothing inappropriate about pointing out that your spamming issues, no need to get toxic and let this serve as a warning.
