### ISSUE TITLE
White cube while sitting

### ISSUE THREAD

**Issue by Stampede2011** [Deltric/Generations#70]
**What is the bug?**
A white cube, which I assume is used for sitting, is visible when on any sitting blocks like Water Floats, Chairs, etc.

**What are the steps to reproduce the bug?**
Place down a sitting block like a Water Float and use F5 to look below the chair.

**What version of Pixelmon and Forge are you on?**
Pixelmon 8.4.2 and Forge 2847

**Please provide any screenshots or crash reports if needed.**
![2021-04-05_16 25 42](https://user-images.githubusercontent.com/12504664/113629536-277a8380-962c-11eb-96d2-d975f9976a40.png)

**Comment by Deltric** [comment]
Fixed pending beta testing
