### ISSUE TITLE
"Shutting Down Internal Server" - Single Player

### ISSUE THREAD

**Issue by OhJudd** [Deltric/Generations#71]
**What is the bug?**
Most of the times when a wild Pokémon initiates a battle or when I initiate a battle and sometimes when I send out my Pokémon out of it's pokeball in a clear open area my game crashes and the message when it's crashing/shutting down  "Shutting Down Internal Server" displays. Takes me back to Minecraft launcher with crash report.

**What are the steps to reproduce the bug?**
A wild Pokémon initiating a battle with me, initiating a battle with a wild Pokémon, and sending my Pokémon out of it's pokeball in a clear open area 

**What version of Pixelmon and Forge are you on?**
Pixelmon version 8.4.2 and Forge version 1.12.2

Mods Installed:
- Biomes O Plenty 1.12.2-7.0.1
- Just Enough Items 1.12.2-4.16.1
- Journey Map 1.12.2-5.7.0
- Optifine 1.12.2
- Pixelmon Generations
- PixelExtras 8.0.0-3.3.0
- PixelHunt 8.0.0
-  PokeDexRewards 1.1.0
- SpongeForge

**Please provide any screenshots or crash reports if needed.**
[crash-2021-04-05_20.47.15-client.txt](https://github.com/Deltric/Generations/files/6262054/crash-2021-04-05_20.47.15-client.txt)
[crash-2021-04-05_20.48.30-client.txt](https://github.com/Deltric/Generations/files/6262055/crash-2021-04-05_20.48.30-client.txt)
[crash-2021-04-05_20.49.48-client.txt](https://github.com/Deltric/Generations/files/6262056/crash-2021-04-05_20.49.48-client.txt)
[crash-2021-04-05_20.51.04-client.txt](https://github.com/Deltric/Generations/files/6262057/crash-2021-04-05_20.51.04-client.txt)
[crash-2021-04-05_20.52.41-client.txt](https://github.com/Deltric/Generations/files/6262058/crash-2021-04-05_20.52.41-client.txt)
[crash-2021-04-05_20.56.24-client.txt](https://github.com/Deltric/Generations/files/6262059/crash-2021-04-05_20.56.24-client.txt)

**Comment by Stampede2011** [comment]
Tested this and it happens when mixing SpongeForge and Pixelmon in a single-player game.

**Comment by OhJudd** [comment]
For sure. Thank you for looking into it. Much appreciated. :)
