### ISSUE TITLE
Unable to give Flabebe hidden ability in pokemon editor

### ISSUE THREAD

**Issue by ItsHypers** [Deltric/Generations#74]
**What is the bug?**
Unable to give Flabebe it's hidden ability (Symbiosis)

**What are the steps to reproduce the bug?**
Get a pokemon editor
give yourself a Flabebe (any form)
go to abilities

**What version of Pixelmon and Forge are you on?**
8.4.2

**Please provide any screenshots or crash reports if needed.**
If you have any screenshots that could visualize the bug
![image](https://user-images.githubusercontent.com/59265736/113941423-f306f300-97f6-11eb-9544-6da6643342b7.png)

**Comment by Dysth** [comment]
Heya @ItsHypers 
Works fine for me- can switch between Symbiosis & Flower Veil repeatedly. Are you doing this on a server with outdated Pokemon Jsons?

**Comment by ItsHypers** [comment]
> Heya @ItsHypers
> Works fine for me- can switch between Symbiosis & Flower Veil repeatedly. Are you doing this on a server with outdated Pokemon Jsons?

Hey!

No we are on the most recent update, and the JSONs are up-to-date too.
