### ISSUE TITLE
Terrain summoning abilities end on the same turn they were set up after the first time the terrain was set up.

### ISSUE THREAD

**Issue by r2d2401** [Deltric/Generations#79]
1. What is the bug? Terrain summoning abilities end on the same turn they were set up after the first time the terrain was set up.

2. What are the steps to reproduce the bug? Set up terrain via one of the abilities WITHOUT a terrain extender, waste turns to remove terrain, after terrain disappears switch in terrain setter.

3. What version of Pixelmon and Forge are you on? Pixelmon version 8.4.2, forge version 14.23.5.2847, however this bug has been persistent since October of 2020.

4. Please provide any screenshots or crash reports if needed.
![please](https://user-images.githubusercontent.com/26104930/114115219-3ca71a80-9897-11eb-9d9f-4714b9696c1f.png)
![just](https://user-images.githubusercontent.com/26104930/114115222-3fa20b00-9897-11eb-900f-755e48b813fa.png)
![fix](https://user-images.githubusercontent.com/26104930/114115226-416bce80-9897-11eb-8e3a-5a98ef5701f4.png)
![this](https://user-images.githubusercontent.com/26104930/114115235-429cfb80-9897-11eb-82e7-2ba3b53dfeb7.png)

**Comment by Dysth** [comment]
@r2d2401 
Heya, I can't seem to reproduce- can you provide me with a full setup and step by step guide?
Here's what I did- which works as intended
Started Battle with Tapu Bulu- Grassy Terrain Activated
Wasted a few turns using status moves (specifically Growl, may not be a legit obtainable move but did the trick)
"The grass disappeared from the battlefield."
Switched into Rillaboom wth Grassy Surge- Grassy Terrain Activated
Grassy Terrain stayed for the next few turns, did not vanish after the first
Neither Pokemon had any held items

**Comment by r2d2401** [comment]
I think I see what you did wrong, I recently just learned that the bug is only affected for each pokemon that sets it individually and not globally, meaning that if Bulu had set the terrain, the bug would only affect Bulu and no one else, but if both Bulu and Rillaboom had set their own terrains and both run out, both would suffer from the bug. Try doing it with only 1 terrain setter or have 2 different terrain setters have their terrains run out. It's also worth noting that the bug will not be in affect if the terrain is overwritten by another terrain or removed by Steam Roller/ Defog, it has to run out by turns.

**Comment by Dysth** [comment]
Thank you, I'm able to reproduce now- working on a fix shortly
