### ISSUE TITLE
Many items are missing a crafting recipe/drop table

### ISSUE THREAD

**Issue by Cavans99** [Deltric/Generations#80]
Many items still miss a way to be obtained/crafted in survival, so I tried to make a list of the ones I noticed.
Some are personal opinions, so I'm not sure this can be considered a bug, let's put it as a suggestion.

Checked pokechests, totems, bosses, pokemon and fishing drop files.
I tried to look in Structures loot tables too, but might have missed something.

- **Can not be obtained at all**:
Many Pokedolls (+ all shiny ones).
Almost every Valuable Item (except for Shards, Mushrooms, Relic items, Perls and Nuggets).
New Mails (Bridge T, Harbor, Shadow, Tropic, Tunnel).
Feathers (Genius and Clever can be dropped by some Pokemon, but are still too rare for what their effect does).
Poke Puffs.
Adrenaline Orb, White/Black/Yellow/Red/Blue Flute, Poke doll (held item), Poke Toy, Utility Umbrella, Sachet, Whipped Dream, Purple Nectar, Bottle Caps, Small Bouquet, Sweet Heart, Super Repel, Max Repel, Guard Spec.

- **Can be obtained, but are a bit too rare**:
Repel, Lava Cookie, Big Malasada, Rage Candy Bar, Lumiose Galette, Shalour Sable, Old Gateau, Casteliacone.
Dream Ball (It gained an effect in Gen. VIII).
Pixelmon Grass (can only be found as some structures decoration, in my opinion it wouldn't be op to make it spawn in random patches in the world).
Dragon Souls, Dark Souls, Sparkling Shards, Rusty Fragments (should have reduced drop rate, but be dropped by many different rare Dragon/Dark/Fairy/Steel Pokémon).

- **Should have a crafting recipe**:
Repel, Super Repel, Max Repel.
Street lamps.
Ultrablocks (not all variants can be found in Ultra Burst).
Reins of Unity.
Bottle Stem (if possible make it craftable with both Pixelmon ruby blocks and Biomes o' plenty ruby blocks, to give a temporary fix to that issue)
Some of the Pillar/Broken Pillar blocks.

**Comment by Dysth** [comment]
Utility Umbrella, Purple Nectar can be crafted
Small bouquet can be obtained but will add another method to obtain
I've addressed essentially everything else on the list- thank you for your work in tracking them down

**Comment by Cavans99** [comment]
@Dysth Thank you for your hard work
