### ISSUE TITLE
Shiny Classic Charmander is not affected by gravity.

### ISSUE THREAD

**Issue by ItsHypers** [Deltric/Generations#82]
**What is the bug?**
The Shiny "Classic" Charmander is not affected by gravity.

**What are the steps to reproduce the bug?**
Give yourself a classic shiny charmander and send it out

**What version of Pixelmon and Forge are you on?**
8.4.2

**Please provide any screenshots or crash reports if needed.**

![image](https://user-images.githubusercontent.com/59265736/114283337-26d55900-9a41-11eb-9fb5-58ede8494de1.png)

**Comment by Deltric** [comment]
Not repeatable

**Comment by ItsHypers** [comment]
> Not repeatable

I gave myself a normal charmander, and in the poke-editor, changed it to classic and made it shiny and nomatter where i sent it out, it was floating

**Comment by Deltric** [comment]
Did exactly that in SP, can test on beta server later.

**Comment by Stampede2011** [comment]
Can confirm that this happens on my testing server as well
