### ISSUE TITLE
Melmetal Gigamax

### ISSUE THREAD

**Issue by Tommy06Pag** [Deltric/Generations#86]
**What is the bug?**
I can't get Melmetal Gigamax with the max soup.

**What are the steps to reproduce the bug?**
Create or give a Melmetal, give the max to it. Not sure if there is another method to obtain it like Urshifu (I tried his method but didn't work), anyway I can set it with the poke editor.

**What version of Pixelmon and Forge are you on?**
8.4.2 (Last technic launcher version)

**Please provide any screenshots or crash reports if needed.**
![2021-04-13_10 32 30](https://user-images.githubusercontent.com/81684661/114523170-5902d880-9c44-11eb-9c26-f92ec802cc89.png)

**Comment by Deltric** [comment]
Please look up the mechanic before reporting as a bug. This is very much intentional.
https://bulbapedia.bulbagarden.net/wiki/Master_Dojo#Max_Soup

**Comment by Tommy06Pag** [comment]
Hi Deltric, sorry for that mistake, I never played sword/shield and I looked the pixelmon wiki, may can I ask to add a note about melmetal?  https://pixelmongenerations.com/wiki/index.php?title=Dynamax
