### ISSUE TITLE
Chisel suggestion

### ISSUE THREAD

**Issue by Tommy06Pag** [Deltric/Generations#89]
Hi, it would be nice if with the chisel you can also create the gigantamax form of the pokemon, like the eternatus eternamax form.

**Comment by Cavans99** [comment]
You can already, for Eternatus you can change the form in the "Form" tab, for all other G-Max there's a button right behind the one for Animation.

**Comment by Tommy06Pag** [comment]
Oh right! I didn't see it, I'm blind xD. Thank you Cavans99! I will close this suggestion.
